from marshmallow import fields
from schema import ma

class ProductSchema(ma.Schema):
    id = fields.Integer(required=False) #id is autogenerated
    name = fields.String(required=True)
    price = fields.Integer(required=True)

    class Meta:
        fields = ("id", "name", "price")

#Create instances of the schemas
product_schema = ProductSchema()
products_schema = ProductSchema(many=True)